# Python Lists

## Creating

In [1]:
# this is a python list
a = [42, 7, 13, 24601, 2001, 3.50]

In [2]:
# this is a list comprehension -- think of it as a sexy for loop

# the following gives us a list in which we multiplied each element in a by 2
z = [i * 2 for i in a]
z

[84, 14, 26, 49202, 4002, 7.0]

## Indexing

In [3]:
# you can index into it
a[0]

42

In [7]:
# what's the 3rd element?
a[2]

13

In [8]:
# indices can also be negative
# this gives you the last element
a[-1]

3.5

## Slicing

In [9]:
# you can also get subsets of the list with slicing
#     a[start:end]
# [start, end)

# this returns the 3rd and 4th entries (indices 2 and 3 -- note we exclude 4!)
a[2:4]

[13, 24601]

In [10]:
# if you leave one side blank, it automatically goes all the way
# first five:
a[:5]

[42, 7, 13, 24601, 2001]

In [13]:
# how do you get the last three elements?
a[-3:]

[24601, 2001, 3.5]

In [14]:
# slices can also skip numbers
# a[start:end:interval]

# this gives us every other number, starting with the first
a[::2]

[42, 13, 2001]

In [15]:
# the interval can also be negative
# what does that do?

a[::-2]

[3.5, 24601, 7]

# Numpy

In [16]:
import numpy as np

## Creating

In [17]:
# numpy arrays can be created from a python list
b = np.array(a)
b

array([4.2000e+01, 7.0000e+00, 1.3000e+01, 2.4601e+04, 2.0010e+03,
       3.5000e+00])

Right now, it looks an awful like a python list, but there are some key points you should know.

numpy arrays are:
- homogeneous (all elements in an array have the same type)
- multidimensional

In [18]:
# Homogeneous: all numpy arrays have an associated data type.
# numbers are usually ints or floats
b.dtype

dtype('float64')

In [19]:
# Multidimensional: numpy arrays can have multiple dimensions, like a nested list.
# We can reshape b into a 3x2 matrix
# Note: this doesn't change b. That's why we assign it to a new variable: m
m = b.reshape(3, 2)
m

array([[4.2000e+01, 7.0000e+00],
       [1.3000e+01, 2.4601e+04],
       [2.0010e+03, 3.5000e+00]])

In [20]:
# Each dimension is called an axis
# The size across each axis is called the shape
# These are two very important concepts!
m.shape

(3, 2)

## Indexing

In [21]:
# We index into numpy arrays much the same way as python lists.
b[0]

42.0

In [22]:
# But N-dimensional arrays mean we can be more expressive with indexing
# This gives us [0th index of axis 0, 1st index of axis 1]
# You can think of this as a grid
# Alternatively, this is like m[0][1]
m[0, 1]

7.0

In [23]:
# We can also pass in multiple indices as a list
# This gives us the 1st, 2nd, and 5th values of b
b[[0, 1, 4]]

array([  42.,    7., 2001.])

In [24]:
# Let's combine these two facts to get the 2nd and 3rd items in the second column of m
m[1:3,1]

array([2.4601e+04, 3.5000e+00])

In [25]:
# We can also incorporate our previous knowledge of slices.
# So to get the second column
# This gives us the entire range on axis 0, and only the 1st index on axis 1
m[:,1]

array([7.0000e+00, 2.4601e+04, 3.5000e+00])

## Math

In [26]:
# numpy gives us a lot of math functions to work with
# I'll only show you a couple, but you can find them all in the documentation

np.sum(b)  # guess what this does?

26667.5

In [27]:
np.mean(b)  # and this?

4444.583333333333

In [28]:
# for convenience, you can also call
b.mean()

4444.583333333333

In [29]:
# you can also apply these functions to only one axis
# only sum across rows (read: apply the sum to axis 1)
np.sum(m, axis=1)

array([   49. , 24614. ,  2004.5])

In [30]:
# numpy has a concept called broadcasting
# It tries to coerce non-matching shapes.
# 2 is a scalar, but we can still multiply m by it
# it just repeats the 2 across all instances of m
m * 2

array([[8.4000e+01, 1.4000e+01],
       [2.6000e+01, 4.9202e+04],
       [4.0020e+03, 7.0000e+00]])

In [31]:
one = np.ones(2)
onet = np.ones([1,2])
m
print(np.matmul(m , np.transpose(m)))

[[1.81300000e+03 1.72753000e+05 8.40665000e+04]
 [1.72753000e+05 6.05209370e+08 1.12116500e+05]
 [8.40665000e+04 1.12116500e+05 4.00401325e+06]]


# Pandas

In [32]:
import pandas as pd

## Creating

Pandas lets us read all sorts of data into a Dataframe. Think of this as a series of lists. Let's look at an example.

In [33]:
df = pd.read_csv("./cereal.csv")
type(df)

pandas.core.frame.DataFrame

In [34]:
# head() gives us the first 10 rows in the dataframe (pd.DataFrame)
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [35]:
# you can think of each column as a list (or a 1D numpy array)
# in practice, these are called pandas Series (pd.Series)
# you can index into the dataframe with a string to get one column
df["name"]

0                                  100% Bran
1                          100% Natural Bran
2                                   All-Bran
3                  All-Bran with Extra Fiber
4                             Almond Delight
5                    Apple Cinnamon Cheerios
6                                Apple Jacks
7                                    Basic 4
8                                  Bran Chex
9                                Bran Flakes
10                              Cap'n'Crunch
11                                  Cheerios
12                     Cinnamon Toast Crunch
13                                  Clusters
14                               Cocoa Puffs
15                                 Corn Chex
16                               Corn Flakes
17                                 Corn Pops
18                             Count Chocula
19                        Cracklin' Oat Bran
20                    Cream of Wheat (Quick)
21                                   Crispix
22        

In [36]:
type(df["name"])

pandas.core.series.Series

## Pandas Series vs Numpy Arrays

In [37]:
# There are many similarities between pd.Series and np.ndarray
# for example:
df["carbo"].mean()

14.597402597402597

In [38]:
# In fact, we can turn pd.Series into a numpy array
# again, this returns a numpy array -- df["carbo"] doesn't change.
df["carbo"].to_numpy()

array([ 5. ,  8. ,  7. ,  8. , 14. , 10.5, 11. , 18. , 15. , 13. , 12. ,
       17. , 13. , 13. , 12. , 22. , 21. , 13. , 12. , 10. , 21. , 21. ,
       11. , 18. , 11. , 14. , 14. , 12. , 14. , 13. , 11. , 15. , 15. ,
       17. , 13. , 12. , 11.5, 14. , 17. , 20. , 21. , 12. , 12. , 16. ,
       16. , 16. , 17. , 15. , 15. , 21. , 18. , 13.5, 11. , 20. , 13. ,
       10. , 14. , -1. , 14. , 10.5, 15. , 23. , 22. , 16. , 19. , 20. ,
        9. , 16. , 15. , 21. , 15. , 16. , 21. , 13. , 17. , 17. , 16. ])

In [39]:
# The key difference is that Series are indexed
# See the 0, 1, ... 76 on the left? That is the index of each item.
# Right now they are just positions, but theoretically they can be any unique identifier for the row
# Think: ID, username, etc
df["carbo"].index

RangeIndex(start=0, stop=77, step=1)

## Indexing into DataFrames and Series

In [40]:
# Indexing is a little bit different in pandas.
# One parallel to what you've been used to is .loc[]
# this is the row at index 0
df.loc[0]

name        100% Bran
mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber              10
carbo               5
sugars              6
potass            280
vitamins           25
shelf               3
weight              1
cups             0.33
rating         68.403
Name: 0, dtype: object

In [41]:
# multiple indices work
df.loc[[1, 2, 3]]

name mfr type  calories  protein  fat  sodium  fiber  \
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912

In [42]:
# caveat: remember that pandas doesn't require zero-indexing. indices can be anything.
# this means slicing might not work all the time (what would df.loc["asdf":"hjkl"] even mean?)
# in the cases that you actually want to index by row number, you can always do that with .iloc[]
# again, this will behave the same as .loc[] with our dataset because our data is 0-indexed
df.iloc[0]

name        100% Bran
mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber              10
carbo               5
sugars              6
potass            280
vitamins           25
shelf               3
weight              1
cups             0.33
rating         68.403
Name: 0, dtype: object

In [43]:
# We can also use boolean indexing by passing a list of booleans like so:
df[[True] + [False] * 76]
# Let me explain:
# - [True] + [False] * 76 gives us a list that looks like [True, False, ..., False] with 1 True and 76 Falses
# - This matches the number of rows in our data (77)
# - pandas returns all the rows with a corresponding True (in this case, only the first one)

name mfr type  calories  protein  fat  sodium  fiber  carbo  sugars  \
0  100% Bran   N    C        70        4    1     130   10.0    5.0       6   

   potass  vitamins  shelf  weight  cups     rating  
0     280        25      3     1.0  0.33  68.402973

In [44]:
# This is powerful because we can also make comparisons with Series and values.
df["protein"] > 3

0      True
1     False
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...  
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56     True
57     True
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
66    False
67     True
68    False
69    False
70    False
71    False
72    False
73    False
74    False
75    False
76    False
Name: protein, Length: 77, dtype: bool

In [45]:
# Combining these two things, we have a very expressive way of filtering.
# This gives us all the rows in which the protein is greater than 3.
df[df["protein"] > 3]

name mfr type  calories  protein  fat  \
0                           100% Bran   N    C        70        4    1   
2                            All-Bran   K    C        70        4    1   
3           All-Bran with Extra Fiber   K    C        50        4    0   
11                           Cheerios   G    C       110        6    2   
41                               Life   Q    C       100        4    2   
43                              Maypo   A    H       100        4    1   
44   Muesli Raisins; Dates; & Almonds   R    C       150        4    3   
45  Muesli Raisins; Peaches; & Pecans   R    C       150        4    3   
56                 Quaker Oat Squares   Q    C       100        4    1   
57                     Quaker Oatmeal   Q    H       100        5    2   
67                          Special K   K    C       110        6    0   

    sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0      130   10.0    5.0       6     280        25      3     1.0  0.33   
2      260    9.0    7.0       5     320        25      3     1.0  0.33   
3      140   14.0    8.0       0     330        25      3     1.0  0.50   
11     290    2.0   17.0       1     105        25      1     1.0  1.25   
41     150    2.0   12.0       6      95        25      2     1.0  0.67   
43       0    0.0   16.0       3      95        25      2     1.0  1.00   
44      95    3.0   16.0      11     170        25      3     1.0  1.00   
45     150    3.0   16.0      11     170        25      3     1.0  1.00   
56     135    2.0   14.0       6     110        25      3     1.0  0.50   
57       0    2.7   -1.0      -1     110         0      1     1.0  0.67   
67     230    1.0   16.0       3      55        25      1     1.0  1.00   

       rating  
0   68.402973  
2   59.425505  
3   93.704912  
11  50.764999  
41  45.328074  
43  54.850917  
44  37.136863  
45  34.139765  
56  49.511874  
57  50.828392  
67  53.131324

## Manipulating Series

Often when we're preprocessing data, we want to make uniform changes to a specific column. We can do this by applying functions.

In [46]:
# Suppose we want to make the cereals more appetizing.
# Let's add "Delicious " to the beginning of every name.

# The pattern is we define a function for a single entry
def make_delicious(name):
    return "Delicious " + name

# and then call apply on the series to apply the function to each element in the series
df["name"].apply(make_delicious)

0                                  Delicious 100% Bran
1                          Delicious 100% Natural Bran
2                                   Delicious All-Bran
3                  Delicious All-Bran with Extra Fiber
4                             Delicious Almond Delight
5                    Delicious Apple Cinnamon Cheerios
6                                Delicious Apple Jacks
7                                    Delicious Basic 4
8                                  Delicious Bran Chex
9                                Delicious Bran Flakes
10                              Delicious Cap'n'Crunch
11                                  Delicious Cheerios
12                     Delicious Cinnamon Toast Crunch
13                                  Delicious Clusters
14                               Delicious Cocoa Puffs
15                                 Delicious Corn Chex
16                               Delicious Corn Flakes
17                                 Delicious Corn Pops
18        

In [47]:
# this returns the changes, but doesn't apply them in place.
# that means on our original dataframe, the cereals are still bland
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [48]:
# we can fix this by assigning the new names to the column.
df["name"] = df["name"].apply(make_delicious)
df.head()

name mfr type  calories  protein  fat  \
0                  Delicious 100% Bran   N    C        70        4    1   
1          Delicious 100% Natural Bran   Q    C       120        3    5   
2                   Delicious All-Bran   K    C        70        4    1   
3  Delicious All-Bran with Extra Fiber   K    C        50        4    0   
4             Delicious Almond Delight   R    C       110        2    2   

   sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0     130   10.0    5.0       6     280        25      3     1.0  0.33   
1      15    2.0    8.0       8     135         0      3     1.0  1.00   
2     260    9.0    7.0       5     320        25      3     1.0  0.33   
3     140   14.0    8.0       0     330        25      3     1.0  0.50   
4     200    1.0   14.0       8      -1        25      3     1.0  0.75   

      rating  
0  68.402973  
1  33.983679  
2  59.425505  
3  93.704912  
4  34.384843

In [49]:
def more_sugar(sugar):
    return sugar +10

df["sugars"].apply(more_sugar)

0     16
1     18
2     15
3     10
4     18
5     20
6     24
7     18
8     16
9     15
10    22
11    11
12    19
13    17
14    23
15    13
16    12
17    22
18    23
19    17
20    10
21    13
22    20
23    15
24    23
25    21
26    17
27    20
28    22
29    22
      ..
47    16
48    19
49    17
50    12
51    20
52    24
53    13
54    10
55    10
56    16
57     9
58    22
59    18
60    16
61    12
62    13
63    10
64    10
65    10
66    25
67    13
68    15
69    13
70    24
71    13
72    13
73    22
74    13
75    13
76    18
Name: sugars, Length: 77, dtype: int64

In [50]:
# here's another example.
# Jackson is a skeptic and doesn't believe calling things "Delicious" makes them taste better.
# But he does think adding sugar will make them taste better.
# How can we add 10 grams of sugar to every cereal?
#df["sugars"] = ???
#df["sugars"] = df["sugars"]+10
df["sugars"]

0      6
1      8
2      5
3      0
4      8
5     10
6     14
7      8
8      6
9      5
10    12
11     1
12     9
13     7
14    13
15     3
16     2
17    12
18    13
19     7
20     0
21     3
22    10
23     5
24    13
25    11
26     7
27    10
28    12
29    12
      ..
47     6
48     9
49     7
50     2
51    10
52    14
53     3
54     0
55     0
56     6
57    -1
58    12
59     8
60     6
61     2
62     3
63     0
64     0
65     0
66    15
67     3
68     5
69     3
70    14
71     3
72     3
73    12
74     3
75     3
76     8
Name: sugars, Length: 77, dtype: int64

# Groups and Aggregates

When we have lots and lots of data, it's more useful to look at aggregate statistics like the mean or median. But sometimes we lose too much detail aggregating across the whole dataset.

The solution is to aggregate across groups. For example, maybe we're less interested in the mean calorie count of all cereals and more interested in the mean for each manufacturer.

In [ ]:
# First, we can see how many (and which) unique manufacturers there are
# Note: this gives us a numpy array
df["mfr"].unique()

In [ ]:
# Now let's group by the manufacturers
# This gives us a groupby object across the dataframe
mfrs = df.groupby("mfr")
mfrs

In [ ]:
# what happens if we try to access the calories column?
mfrs["calories"]

In [ ]:
# now let's try to get the mean
mfrs["calories"].mean()

In [ ]:
# we can also aggregate across multiple columns, and even use different aggregations
# let's get the average calorie count but the maximum protein
mfrs[["calories", "protein"]].agg({"calories": "mean", "protein": "max"})

# Exercises

Unless otherwise noted, these should be one line of code.

In [51]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

# get a list containing the last 3 elements of a

a[-3:]

# reverse the list
a[::-1]
# get a list where each entry in a is cubed (so the new list is [1, 4, 9, 16, 25, 36])
[i**3 for i in a]

[1, 8, 27, 64, 125, 216]

In [52]:
# create a numpy array from this list
b = np.asarray(a) # change this


In [53]:
# find the mean of b
np.mean(b)

3.5

In [54]:
# change b from a length-6 list to a 2x3 matrix
b_matrix = b.reshape(2,3)
b_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
# find the mean value of each row
np.mean(b_matrix, axis = 1)

array([2., 5.])

In [56]:
# find the mean value of each column
np.mean(b_matrix, axis = 0)

array([2.5, 3.5, 4.5])

In [57]:
# find the third column of b
b_matrix[:,2]

array([3, 6])

In [58]:
# get a list where each entry in b is cubed (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach
b*b

array([ 1,  4,  9, 16, 25, 36])

In [59]:
# load in the "starbucks.csv" dataset
df = pd.read_csv("./starbucks.csv")


In [60]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?
df['Calories'].mean()

193.87190082644628

In [61]:
# how many different categories of beverages are there?
df['Beverage_category'].unique()

array(['Coffee', 'Classic Espresso Drinks', 'Signature Espresso Drinks',
       'Tazo® Tea Drinks', 'Shaken Iced Beverages', 'Smoothies',
       'Frappuccino® Blended Coffee', 'Frappuccino® Light Blended Coffee',
       'Frappuccino® Blended Crème'], dtype=object)

In [62]:
# what is the average # calories for each beverage category?
bevs = df.groupby("Beverage_category")
bevs["Calories"].mean()


Beverage_category
Classic Espresso Drinks              140.172414
Coffee                                 4.250000
Frappuccino® Blended Coffee          276.944444
Frappuccino® Blended Crème           233.076923
Frappuccino® Light Blended Coffee    162.500000
Shaken Iced Beverages                114.444444
Signature Espresso Drinks            250.000000
Smoothies                            282.222222
Tazo® Tea Drinks                     177.307692
Name: Calories, dtype: float64

In [63]:
# what beverage preparation includes the most sugar?

#Venti Nonfat Milk  and Whole Milk            

bevs_prep = df.groupby("Beverage_prep")

bevs_prep[" Sugars (g)"].max()



Beverage_prep
2% Milk               74
Doppio                 0
Grande                65
Grande Nonfat Milk    62
Short                 33
Short Nonfat Milk     29
Solo                   0
Soymilk               80
Tall                  49
Tall Nonfat Milk      45
Venti                 83
Venti Nonfat Milk     84
Whole Milk            84
Name:  Sugars (g), dtype: int64

In [65]:
# what is the average % daily value calcium content for each beverage?
# HINT: make sure your columns have the datatypes you want
# (you can use more than one line for this one)

df[" Calcium (% DV) "] = df[" Calcium (% DV) "].str.replace('%', '').astype(int)

df[" Calcium (% DV) "]
bevs2 = df.groupby("Beverage_category")

bevs2[" Calcium (% DV) "].mean()

Beverage_category
Classic Espresso Drinks              27.344828
Coffee                                0.500000
Frappuccino® Blended Coffee          12.277778
Frappuccino® Blended Crème           13.846154
Frappuccino® Light Blended Coffee    11.333333
Shaken Iced Beverages                 4.000000
Signature Espresso Drinks            31.375000
Smoothies                            13.333333
Tazo® Tea Drinks                     23.653846
Name:  Calcium (% DV) , dtype: float64

In [74]:
# It's bulking season. What drink should Jackson get so that he maximizes protein but minimizes fat?
# (you can use more than one line for this one)

###ANSWER:
#from this we can see that the Banana Chocolate Smoothie preped with Grande Nonfat Milk provides the most protein with the
# least fat

bevs3 = df.groupby(["Beverage", "Beverage_prep"])
bevs3[[" Protein (g) "," Total Fat (g)"]].agg({" Protein (g) ": "max", " Total Fat (g)": "min"})

Protein (g)   \
Beverage                                      Beverage_prep                       
Banana Chocolate Smoothie                     2% Milk                      20.0   
                                              Grande Nonfat Milk           20.0   
                                              Soymilk                      19.0   
Brewed Coffee                                 Grande                        1.0   
                                              Short                         0.3   
                                              Tall                          0.5   
                                              Venti                         1.0   
Caffè Americano                               Grande                        1.0   
                                              Short                         0.4   
                                              Tall                          1.0   
                                              Venti                         1.0   
Caffè Latte                                   2% Milk                      16.0   
                                              Grande Nonfat Milk           13.0   
                                              Short Nonfat Milk             6.0   
                                              Soymilk                      13.0   
                                              Tall Nonfat Milk             10.0   
                                              Venti Nonfat Milk            16.0   
Caffè Mocha (Without Whipped Cream)           2% Milk                      17.0   
                                              Grande Nonfat Milk           13.0   
                                              Short Nonfat Milk             7.0   
                                              Soymilk                      14.0   
                                              Tall Nonfat Milk             10.0   
                                              Venti Nonfat Milk            17.0   
Cappuccino                                    2% Milk                      10.0   
                                              Grande Nonfat Milk            8.0   
                                              Short Nonfat Milk             5.0   
                                              Soymilk                       9.0   
                                              Tall Nonfat Milk              6.0   
                                              Venti Nonfat Milk            10.0   
Caramel                                       Grande Nonfat Milk            3.0   
...                                                                         ...   
Tazo® Full-Leaf Tea Latte                     Short Nonfat Milk             4.0   
                                              Soymilk                       7.0   
                                              Tall Nonfat Milk              5.0   
                                              Venti Nonfat Milk             9.0   
Tazo® Green Tea Latte                         2% Milk                      17.0   
                                              Grande Nonfat Milk           14.0   
                                              Short Nonfat Milk             7.0   
                                              Soymilk                      14.0   
                                              Tall Nonfat Milk             11.0   
                                              Venti Nonfat Milk            18.0   
Tazo® Tea                                     Grande                        0.0   
                                              Short                         0.0   
                                              Tall                          0.0   
                                              Venti                         0.0   
Vanilla Bean (Without Whipped Cream)          Grande Nonfat Milk            5.0   
                                              Soymilk                       3.0   


NameError: name 'df' is not defined